const SHUFFLE_ARRAY = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const SHUFFLE_NUMBER = 0.5;
const SLICE_MIN_NUMBER = 0;
const SLICE_MAX_NUMBER = 3;

const BASEBALL_ANSWER_LENGTH = 3;
const BASEBALL_ANSWER_MIN = 1;
const BASEBALL_ANSWER_MAX = 9;
const THREE_STRIKE = 3;

const GAME_START_NUMBER = 1;
const GAME_LOG_NUMBER = 2;
const GAME_DATA_NUMBER = 3;
const GAME_END_NUMBER = 9;

const END_NUMBER = 0;
const EMPTY_NUMBER = 0;

const LEAVE_IN_THE_MIDDLE_LENGTH = 1;
const LEAVE_IN_THE_MIDDLE_NUMBER = 9;

export {
  SHUFFLE_ARRAY,
  SHUFFLE_NUMBER,
  SLICE_MIN_NUMBER,
  SLICE_MAX_NUMBER,
  BASEBALL_ANSWER_LENGTH,
  BASEBALL_ANSWER_MIN,
  BASEBALL_ANSWER_MAX,
  THREE_STRIKE,
  GAME_START_NUMBER,
  GAME_LOG_NUMBER,
  GAME_DATA_NUMBER,
  GAME_END_NUMBER,
  END_NUMBER,
  EMPTY_NUMBER,
  LEAVE_IN_THE_MIDDLE_LENGTH,
  LEAVE_IN_THE_MIDDLE_NUMBER,
};
